export interface Producto{
    id:number,
    nombre:string,
    titulo:string,
    descuento:string,
    tienda:string,
    cantidad:number,
    categoria:string,
    descripcion:string,
    precio_antes:number,
    precio:number,
    beneficios:string,
    modo_de_uso:string,
    detalle:string,
    img:string,
}